version: '3.7'
services:
  nginx:
    build:
      context: ./docker/nginx/
    ports:
      - "80:80"
    depends_on:
      - "crawl"

  crawl:
    build:
      context: ./docker/golang/
    volumes:
      - ./:/app/
    ports:
      - "9000"
    working_dir: "/app"
    privileged: true
    tty: true

  db:
    build: ./docker/db
    ports:
      - "63311:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db_crawl