name: 'Build Project'

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        cache: false

    - name: Build
      run: |
        make set_env_project
        make build_project

    - name: Test
      run: |
        make set_env_project
        make test_project