name: 'Build Project'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        cache: false

    - name: Build
      run: |
        export GOCACHE="/root/.cache/go-build"
        export GOPATH="/root/go"
        export GOENV="/root/.config/go/env"
        go build -v ./...

    - name: Test
      run: |
        export GOCACHE="/root/.cache/go-test"
        export GOPATH="/root/go"
        export GOENV="/root/.config/go/env"
        go test -v ./...

  deploy:
    runs-on: self-hosted
    needs:
      - build
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    steps:
      - name: Deploy Product
        run: |
          export GOCACHE="/root/.cache/go-build"
          export GOPATH="/root/go"
          export GOENV="/root/.config/go/env"
          ./build.sh
          sudo systemctl restart app_web