name: 'Build Project'

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        cache: false

    - name: Build
      run: |
        export GOCACHE="/root/.cache/go-build"
        export GOPATH="/root/go"
        export GOENV="/root/.config/go/env"
        go build -v ./...

    - name: Test
      run: |
        make step_project_test
