name: 'Deploy Project'

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: false
      - name: Deploy Product
        run: |
          make set_env_project_build
          make deploy_project