name: 'Deploy Project'

on:
  #push:
    #branches: [ "master" ]
  push:
    branches:
      - 'aal_*'
  pull_request:
    branches:
      - main
      - '*_release'

jobs:
  deploy:
    runs-on: self-hosted
    if: startsWith(github.ref, 'release') || endsWith(github.ref, 'staging') || github.base_ref == 'main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          cache: false
      - name: Deploy Product
        env:
          ENV_DB_USERNAME: ${{ secrets.ENV_DB_USERNAME }}
          ENV_DB_PASSWORD: ${{ secrets.ENV_DB_PASSWORD }}
          ENV_DB_HOST: ${{ secrets.ENV_DB_HOST }}
          ENV_DB_NAME: ${{ secrets.ENV_DB_NAME }}
          ENV_URL_WEBHOOK_DISCORD: ${{ secrets.URL_WEBHOOK_DISCORD }}
          ENV_TYPESENSE_URL: ${{ secrets.ENV_TYPESENSE_URL }}
          ENV_TYPESENSE_API_KEY: ${{ secrets.ENV_TYPESENSE_API_KEY }}
        run: |
          export GOCACHE="/root/.cache/go-build"
          export GOPATH="/root/go"
          export GOENV="/root/.config/go/env"
          envsubst < app_deploy.yaml > app.yaml
          make deploy_project
